module.exports = {
  "callAdapter": require('./callAdapter.js'),
  "common": {
    "constants": require('./common/constants.js'),
    "error": require('./common/error.js'),
    "sensitive-aes-cipher": require('./common/sensitive-aes-cipher.js'),
    "universal": require('./common/universal.js'),
    "utils": require('./common/utils.js'),
    "validator": require('./common/validator.js'),
  },
  "config": {
    "permission": require('./config/permission.js'),
  },
  "index.obj": require('./index.obj.js'),
  "lang": {
    "en": require('./lang/en.js'),
    "index": require('./lang/index.js'),
    "zh-hans": require('./lang/zh-hans.js'),
  },
  "lib": {
    "npm": {
      "index": require('./lib/npm/index.js'),
    },
    "third-party": {
      "alipay": {
        "account": {
          "index": require('./lib/third-party/alipay/account/index.js'),
          "protocols": require('./lib/third-party/alipay/account/protocols.js'),
        },
        "alipayBase": require('./lib/third-party/alipay/alipayBase.js'),
      },
      "apple": {
        "account": {
          "index": require('./lib/third-party/apple/account/index.js'),
        },
        "rsa-public-key-pem": require('./lib/third-party/apple/rsa-public-key-pem.js'),
      },
      "huawei": {
        "account": {
          "index": require('./lib/third-party/huawei/account/index.js'),
        },
        "base": require('./lib/third-party/huawei/base.js'),
        "normalize": require('./lib/third-party/huawei/normalize.js'),
      },
      "index": require('./lib/third-party/index.js'),
      "qq": {
        "account": {
          "index": require('./lib/third-party/qq/account/index.js'),
        },
        "normalize": require('./lib/third-party/qq/normalize.js'),
      },
      "share": {
        "certutil": require('./lib/third-party/share/certutil.js'),
        "create-api": require('./lib/third-party/share/create-api.js'),
      },
      "weixin": {
        "account": {
          "index": require('./lib/third-party/weixin/account/index.js'),
        },
        "normalize": require('./lib/third-party/weixin/normalize.js'),
        "utils": require('./lib/third-party/weixin/utils.js'),
      },
    },
    "utils": {
      "account": require('./lib/utils/account.js'),
      "captcha": require('./lib/utils/captcha.js'),
      "config": require('./lib/utils/config.js'),
      "fission": require('./lib/utils/fission.js'),
      "huawei": require('./lib/utils/huawei.js'),
      "login": require('./lib/utils/login.js'),
      "logout": require('./lib/utils/logout.js'),
      "password": require('./lib/utils/password.js'),
      "qq": require('./lib/utils/qq.js'),
      "register": require('./lib/utils/register.js'),
      "relate": require('./lib/utils/relate.js'),
      "sms": require('./lib/utils/sms.js'),
      "unified-login": require('./lib/utils/unified-login.js'),
      "univerify": require('./lib/utils/univerify.js'),
      "update-user-info": require('./lib/utils/update-user-info.js'),
      "utils": require('./lib/utils/utils.js'),
      "verify-code": require('./lib/utils/verify-code.js'),
      "weixin": require('./lib/utils/weixin.js'),
    },
  },
  "middleware": {
    "access-control": require('./middleware/access-control.js'),
    "auth": require('./middleware/auth.js'),
    "index": require('./middleware/index.js'),
    "rbac": require('./middleware/rbac.js'),
    "uni-id-log": require('./middleware/uni-id-log.js'),
    "validate": require('./middleware/validate.js'),
    "verify-request-sign": require('./middleware/verify-request-sign.js'),
  },
  "module": {
    "account": {
      "close-account": require('./module/account/close-account.js'),
      "get-account-info": require('./module/account/get-account-info.js'),
      "get-realname-info": require('./module/account/get-realname-info.js'),
      "index": require('./module/account/index.js'),
      "reset-pwd-by-email": require('./module/account/reset-pwd-by-email.js'),
      "reset-pwd-by-sms": require('./module/account/reset-pwd-by-sms.js'),
      "set-pwd": require('./module/account/set-pwd.js'),
      "update-pwd": require('./module/account/update-pwd.js'),
    },
    "admin": {
      "add-user": require('./module/admin/add-user.js'),
      "index": require('./module/admin/index.js'),
      "update-user": require('./module/admin/update-user.js'),
    },
    "dev": {
      "get-supported-login-type": require('./module/dev/get-supported-login-type.js'),
      "index": require('./module/dev/index.js'),
    },
    "external": {
      "index": require('./module/external/index.js'),
      "login": require('./module/external/login.js'),
      "register": require('./module/external/register.js'),
      "update-user-info": require('./module/external/update-user-info.js'),
    },
    "facial-recognition-verify": {
      "get-auth-result": require('./module/facial-recognition-verify/get-auth-result.js'),
      "get-certify-id": require('./module/facial-recognition-verify/get-certify-id.js'),
      "index": require('./module/facial-recognition-verify/index.js'),
    },
    "fission": {
      "accept-invite": require('./module/fission/accept-invite.js'),
      "get-invited-user": require('./module/fission/get-invited-user.js'),
      "index": require('./module/fission/index.js'),
    },
    "login": {
      "index": require('./module/login/index.js'),
      "login-by-alipay": require('./module/login/login-by-alipay.js'),
      "login-by-apple": require('./module/login/login-by-apple.js'),
      "login-by-baidu": require('./module/login/login-by-baidu.js'),
      "login-by-dingtalk": require('./module/login/login-by-dingtalk.js'),
      "login-by-douyin": require('./module/login/login-by-douyin.js'),
      "login-by-email-code": require('./module/login/login-by-email-code.js'),
      "login-by-email-link": require('./module/login/login-by-email-link.js'),
      "login-by-facebook": require('./module/login/login-by-facebook.js'),
      "login-by-google": require('./module/login/login-by-google.js'),
      "login-by-huawei": require('./module/login/login-by-huawei.js'),
      "login-by-qq": require('./module/login/login-by-qq.js'),
      "login-by-sms": require('./module/login/login-by-sms.js'),
      "login-by-taobao": require('./module/login/login-by-taobao.js'),
      "login-by-toutiao": require('./module/login/login-by-toutiao.js'),
      "login-by-univerify": require('./module/login/login-by-univerify.js'),
      "login-by-weibo": require('./module/login/login-by-weibo.js'),
      "login-by-weixin-mobile": require('./module/login/login-by-weixin-mobile.js'),
      "login-by-weixin": require('./module/login/login-by-weixin.js'),
      "login": require('./module/login/login.js'),
    },
    "logout": {
      "index": require('./module/logout/index.js'),
      "logout": require('./module/logout/logout.js'),
    },
    "multi-end": {
      "authorize-app-login": require('./module/multi-end/authorize-app-login.js'),
      "index": require('./module/multi-end/index.js'),
      "remove-authorized-app": require('./module/multi-end/remove-authorized-app.js'),
      "set-authorized-app": require('./module/multi-end/set-authorized-app.js'),
      "utils": require('./module/multi-end/utils.js'),
    },
    "register": {
      "index": require('./module/register/index.js'),
      "register-admin": require('./module/register/register-admin.js'),
      "register-user-by-email": require('./module/register/register-user-by-email.js'),
      "register-user": require('./module/register/register-user.js'),
    },
    "relate": {
      "bind-alipay": require('./module/relate/bind-alipay.js'),
      "bind-apple": require('./module/relate/bind-apple.js'),
      "bind-huawei": require('./module/relate/bind-huawei.js'),
      "bind-mobile-by-huawei": require('./module/relate/bind-mobile-by-huawei.js'),
      "bind-mobile-by-mp-weixin": require('./module/relate/bind-mobile-by-mp-weixin.js'),
      "bind-mobile-by-sms": require('./module/relate/bind-mobile-by-sms.js'),
      "bind-mobile-by-univerify": require('./module/relate/bind-mobile-by-univerify.js'),
      "bind-qq": require('./module/relate/bind-qq.js'),
      "bind-weixin": require('./module/relate/bind-weixin.js'),
      "index": require('./module/relate/index.js'),
      "unbind-alipay": require('./module/relate/unbind-alipay.js'),
      "unbind-apple": require('./module/relate/unbind-apple.js'),
      "unbind-huawei": require('./module/relate/unbind-huawei.js'),
      "unbind-qq": require('./module/relate/unbind-qq.js'),
      "unbind-weixin": require('./module/relate/unbind-weixin.js'),
    },
    "utils": {
      "index": require('./module/utils/index.js'),
      "refresh-token": require('./module/utils/refresh-token.js'),
      "secure-network-handshake-by-weixin": require('./module/utils/secure-network-handshake-by-weixin.js'),
      "set-push-cid": require('./module/utils/set-push-cid.js'),
    },
    "verify": {
      "create-captcha": require('./module/verify/create-captcha.js'),
      "index": require('./module/verify/index.js'),
      "refresh-captcha": require('./module/verify/refresh-captcha.js'),
      "send-email-code": require('./module/verify/send-email-code.js'),
      "send-email-link": require('./module/verify/send-email-link.js'),
      "send-sms-code": require('./module/verify/send-sms-code.js'),
    },
  },
};
