'use strict'

const DEFAULT_NICKNAME = '微信用户'
const DEFAULT_ROLE = 'member'

const COUPLE_STATUS_PENDING = 0
const COUPLE_STATUS_BOUND = 1
const COUPLE_STATUS_UNBOUND = 2
const COUPLE_STATUS_CLOSED = 3
const COUPLE_STATUS_CANCELLED = 4

const COUPLE_LOCK_TTL = 15 * 1000
const COUPLE_LOCK_RETRY_COUNT = 3
const COUPLE_LOCK_RETRY_DELAY = 120

const COUPLE_STATUS_TEXT = {
	[COUPLE_STATUS_PENDING]: '待确认',
	[COUPLE_STATUS_BOUND]: '已绑定',
	[COUPLE_STATUS_UNBOUND]: '已解绑',
	[COUPLE_STATUS_CLOSED]: '已关闭',
	[COUPLE_STATUS_CANCELLED]: '已撤回'
}

module.exports = {
	DEFAULT_NICKNAME,
	DEFAULT_ROLE,
	COUPLE_STATUS_PENDING,
	COUPLE_STATUS_BOUND,
	COUPLE_STATUS_UNBOUND,
	COUPLE_STATUS_CLOSED,
	COUPLE_STATUS_CANCELLED,
	COUPLE_LOCK_TTL,
	COUPLE_LOCK_RETRY_COUNT,
	COUPLE_LOCK_RETRY_DELAY,
	COUPLE_STATUS_TEXT
}
